language: node_js
node_js:
- node
- lts/*
sudo: false
cache:
  directories:
  - "~/.npm"
install:
- npm i
stages:
- test
- name: deploy
jobs:
  include:
  - stage: test
    name: Run the tests
    script:
    - node --version
    - npm --version
    - npm start -- --version
    - npm start -- --help
    - npm test
  - stage: deploy
    name: Deploy to NPM
    deploy:
      provider: npm
      email: 'services@netlify.com'
      api_key:
        secure: "MPCF4xpvrsmcOxVcEKutdSVA0T6fH3q/QB59NnQ7AgJaqBXrqr61sRD/C+SMf47B1d/CJbm9iYlD/D2IPZ0yWgpt2SwFFpZi9ezbUqBwC05TbKj+j/uP0klDMQ9QZSNXOkSGCsjOc2F1NyxN1hNJJ+ElBO4EpU9+M0s/sazTUqM="
      on:
        tags: true
        repo: netlify/cli
after_success:
- npm run report
env:
  global:
  - secure: fN+jOrIf8/RZINDXDcG/KOS92LaiYdMiPcUtEEsJiz6dHmkxNYlMgTmTTTHLF/3Wjl3YP6xKkHaetvThoRlNHByC2uTeBUqHkCYwXBOpRpycekheIsz96WPyRidJwLAi5Jx+NnoAp8mFl/SFtQouu2IjxK/GUtPAg2wlCsFYYSU=
