version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/cli

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "npm-shrinkwrap.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "npm-shrinkwrap.json" }}

      # run tests!
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/cli
    requires:
      - build
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /.*/
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "npm-shrinkwrap.json" }}
            - npm-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "npm-shrinkwrap.json" }}
      - run: npm publish

