version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "npm-shrinkwrap.json" }}
            - npm-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "npm-shrinkwrap.json" }}
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "npm-shrinkwrap.json" }}
            - npm-dependencies-
      - run: npm install

workflows:
  version: 2
  test-n-deploy:
    jobs:
      - test:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
